services:
  nest-demo-pt21a:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/src
    env_file:
      - .env.development
    depends_on:
      - postgres
    networks:
      - pepe

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pepe

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  pepe:
    driver: bridge